# Portainer + Agent - deploy inicial via docker stack (variáveis: DOMAIN_PORTAINER, admin via secret)
services:
  agent:
    image: portainer/agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/volumes:/var/lib/docker/volumes:ro
    networks:
      - main
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    security_opt:
      - no-new-privileges:true
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux
      resources:
        limits:
          cpus: "0.5"
          memory: 128M
      restart_policy:
        condition: any
        delay: 5s

  portainer:
    image: portainer/portainer-ce:latest
    command: -H tcp://tasks.agent:9001 --tlsskipverify --admin-password-file /run/secrets/portainer_admin_password
    secrets:
      - portainer_admin_password
    volumes:
      - portainer_data:/data
    networks:
      - main
    ports:
      - target: 9000
        published: 9000
        mode: host
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:9000/api/system/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    security_opt:
      - no-new-privileges:true
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.portainer.rule=Host(`${DOMAIN_PORTAINER}`)"
        - "traefik.http.routers.portainer.entrypoints=websecure"
        - "traefik.http.routers.portainer.tls=true"
        - "traefik.http.routers.portainer.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.portainer.loadbalancer.server.port=9000"
        - "traefik.http.routers.portainer.middlewares=security-headers@file,rate-limit@file"
        - "traefik.swarm.network=main"

secrets:
  portainer_admin_password:
    external: true
    name: portainer_admin_password

networks:
  main:
    external: true
    name: main

volumes:
  portainer_data:
    external: true
    name: portainer_data
